// GENERATED by tool/icons/build.js — do not edit by hand.
// Sources: tool/icons/src/*.svg · codepoints: tool/icons/codepoints.json

import 'package:flutter/widgets.dart';

/// The Hero icon font (`assets/fonts/hero_icons.ttf`, family [fontFamily]).
///
/// Directional icons set `matchTextDirection`, so they flip in RTL.
@staticIconProvider
abstract final class HeroIcons {
  /// The font family declared in pubspec.yaml.
  static const String fontFamily = 'HeroIcons';

  /// Arrow pointing to the start side (left in LTR), round head.
  static const IconData back = IconData(
    0xE000,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Arrow pointing to the end side.
  static const IconData arrowForward = IconData(
    0xE001,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Arrow up.
  static const IconData arrowUp = IconData(0xE002, fontFamily: fontFamily);

  /// Arrow down.
  static const IconData arrowDown = IconData(0xE003, fontFamily: fontFamily);

  /// Diagonal arrow toward top-start (search "fill in").
  static const IconData arrowUpStart = IconData(
    0xE004,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Diagonal arrow toward top-end.
  static const IconData arrowUpEnd = IconData(
    0xE005,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Disclosure chevron toward the end side.
  static const IconData chevronEnd = IconData(
    0xE006,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Chevron toward the start side.
  static const IconData chevronStart = IconData(
    0xE007,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Chevron down.
  static const IconData chevronDown = IconData(0xE008, fontFamily: fontFamily);

  /// Chevron up.
  static const IconData chevronUp = IconData(0xE009, fontFamily: fontFamily);

  /// X.
  static const IconData close = IconData(0xE00A, fontFamily: fontFamily);

  /// X in a circle (outline).
  static const IconData closeCircle = IconData(0xE00B, fontFamily: fontFamily);

  /// Solid disc, x knocked out.
  static const IconData closeCircleFill = IconData(
    0xE00C,
    fontFamily: fontFamily,
  );

  /// +.
  static const IconData plus = IconData(0xE00D, fontFamily: fontFamily);

  /// −.
  static const IconData minus = IconData(0xE00E, fontFamily: fontFamily);

  /// − in a circle.
  static const IconData minusCircle = IconData(0xE00F, fontFamily: fontFamily);

  /// Check mark.
  static const IconData check = IconData(0xE010, fontFamily: fontFamily);

  /// Two check marks (read receipt).
  static const IconData checkDouble = IconData(0xE011, fontFamily: fontFamily);

  /// Check in a circle (outline).
  static const IconData checkCircle = IconData(0xE012, fontFamily: fontFamily);

  /// Solid disc, check knocked out.
  static const IconData checkCircleFill = IconData(
    0xE013,
    fontFamily: fontFamily,
  );

  /// I in a circle.
  static const IconData info = IconData(0xE014, fontFamily: fontFamily);

  /// ! in a circle.
  static const IconData warning = IconData(0xE015, fontFamily: fontFamily);

  /// A lone ! (small badge use).
  static const IconData exclamation = IconData(0xE016, fontFamily: fontFamily);

  /// ? in a circle.
  static const IconData help = IconData(
    0xE017,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Magnifier, handle to bottom-end.
  static const IconData search = IconData(0xE018, fontFamily: fontFamily);

  /// Two slider lines with knobs.
  static const IconData filter = IconData(0xE019, fontFamily: fontFamily);

  /// Up + down arrows side by side.
  static const IconData sort = IconData(0xE01A, fontFamily: fontFamily);

  /// Left + right arrows stacked.
  static const IconData swapHorizontal = IconData(
    0xE01B,
    fontFamily: fontFamily,
  );

  /// Three dots vertical.
  static const IconData moreVertical = IconData(0xE01C, fontFamily: fontFamily);

  /// Circular arrow.
  static const IconData refresh = IconData(0xE01D, fontFamily: fontFamily);

  /// Clock face with a back-circling arrow.
  static const IconData history = IconData(0xE01E, fontFamily: fontFamily);

  /// Two overlapping rounded sheets.
  static const IconData copy = IconData(0xE01F, fontFamily: fontFamily);

  /// Pencil with a base line.
  static const IconData edit = IconData(0xE020, fontFamily: fontFamily);

  /// Bin with lid + 2 slots.
  static const IconData trash = IconData(0xE021, fontFamily: fontFamily);

  /// House, rounded roof (Home tab line).
  static const IconData home = IconData(0xE022, fontFamily: fontFamily);

  /// Solid house, door knocked out.
  static const IconData homeFill = IconData(0xE023, fontFamily: fontFamily);

  /// THE HERO BAG silhouette: rounded bag + arched handle (the mark's bag, no cape, no h).
  static const IconData bag = IconData(0xE024, fontFamily: fontFamily);

  /// Shopping cart, two wheels.
  static const IconData cart = IconData(0xE025, fontFamily: fontFamily);

  /// Cart with a small + in the basket.
  static const IconData cartAdd = IconData(0xE026, fontFamily: fontFamily);

  /// Grocery basket with handle arc.
  static const IconData basket = IconData(0xE027, fontFamily: fontFamily);

  /// Storefront with scalloped awning.
  static const IconData store = IconData(0xE028, fontFamily: fontFamily);

  /// Clipboard/receipt sheet with 2 lines.
  static const IconData orders = IconData(0xE029, fontFamily: fontFamily);

  /// Clipboard with a check.
  static const IconData ordersDone = IconData(0xE02A, fontFamily: fontFamily);

  /// Long receipt with zigzag bottom + lines.
  static const IconData receipt = IconData(0xE02B, fontFamily: fontFamily);

  /// Scooter side view carrying a Hero bag box on the back (faces end side when directional).
  static const IconData delivery = IconData(0xE02C, fontFamily: fontFamily);

  /// Map pin outline with a round hole.
  static const IconData pin = IconData(0xE02E, fontFamily: fontFamily);

  /// Solid pin, hole knocked out.
  static const IconData pinFill = IconData(0xE02F, fontFamily: fontFamily);

  /// Clock face 10:10 hands.
  static const IconData clock = IconData(0xE030, fontFamily: fontFamily);

  /// Hourglass.
  static const IconData hourglass = IconData(0xE031, fontFamily: fontFamily);

  /// Calendar sheet with 2 rings.
  static const IconData calendar = IconData(0xE032, fontFamily: fontFamily);

  /// Calendar with a check.
  static const IconData calendarCheck = IconData(
    0xE033,
    fontFamily: fontFamily,
  );

  /// 5-point star outline, rounded points.
  static const IconData star = IconData(0xE034, fontFamily: fontFamily);

  /// Solid star.
  static const IconData starFill = IconData(0xE035, fontFamily: fontFamily);

  /// Star inside a coin circle (loyalty points).
  static const IconData points = IconData(0xE036, fontFamily: fontFamily);

  /// Solid coin, star knocked out.
  static const IconData pointsFill = IconData(0xE037, fontFamily: fontFamily);

  /// Heart outline.
  static const IconData heart = IconData(0xE038, fontFamily: fontFamily);

  /// Solid heart.
  static const IconData heartFill = IconData(0xE039, fontFamily: fontFamily);

  /// Gift box with bow.
  static const IconData gift = IconData(0xE03A, fontFamily: fontFamily);

  /// Price tag with hole.
  static const IconData tag = IconData(0xE03B, fontFamily: fontFamily);

  /// Ticket with side notches + dashed divider.
  static const IconData voucher = IconData(0xE03C, fontFamily: fontFamily);

  /// % sign.
  static const IconData percent = IconData(0xE03D, fontFamily: fontFamily);

  /// Scalloped badge with %.
  static const IconData discount = IconData(0xE03E, fontFamily: fontFamily);

  /// Wallet with flap + clasp dot.
  static const IconData wallet = IconData(0xE03F, fontFamily: fontFamily);

  /// Stacked coins.
  static const IconData savings = IconData(0xE040, fontFamily: fontFamily);

  /// 3-point crown (Hero Pro).
  static const IconData crown = IconData(0xE041, fontFamily: fontFamily);

  /// Lightning bolt.
  static const IconData bolt = IconData(0xE042, fontFamily: fontFamily);

  /// Flame outline.
  static const IconData flame = IconData(0xE043, fontFamily: fontFamily);

  /// Solid flame.
  static const IconData flameFill = IconData(0xE044, fontFamily: fontFamily);

  /// One big 4-point sparkle + a small one.
  static const IconData sparkle = IconData(0xE045, fontFamily: fontFamily);

  /// Rocket.
  static const IconData rocket = IconData(0xE046, fontFamily: fontFamily);

  /// Zigzag line up with arrow head.
  static const IconData trendingUp = IconData(
    0xE047,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// 2x2 rounded squares, one a circle.
  static const IconData category = IconData(0xE048, fontFamily: fontFamily);

  /// Head + shoulders (account).
  static const IconData person = IconData(0xE049, fontFamily: fontFamily);

  /// Two people.
  static const IconData people = IconData(0xE04A, fontFamily: fontFamily);

  /// Headset with mic.
  static const IconData support = IconData(0xE04B, fontFamily: fontFamily);

  /// Phone handset.
  static const IconData phone = IconData(0xE04C, fontFamily: fontFamily);

  /// Speech bubble with 3 dots.
  static const IconData chat = IconData(0xE04D, fontFamily: fontFamily);

  /// Solid speech bubble.
  static const IconData chatFill = IconData(0xE04E, fontFamily: fontFamily);

  /// Speech bubble with +.
  static const IconData chatAdd = IconData(0xE04F, fontFamily: fontFamily);

  /// Envelope.
  static const IconData mail = IconData(0xE050, fontFamily: fontFamily);

  /// Bell.
  static const IconData bell = IconData(0xE051, fontFamily: fontFamily);

  /// Megaphone.
  static const IconData megaphone = IconData(0xE052, fontFamily: fontFamily);

  /// Tray with a dip.
  static const IconData inbox = IconData(0xE053, fontFamily: fontFamily);

  /// Page with folded corner + lines.
  static const IconData document = IconData(0xE054, fontFamily: fontFamily);

  /// Padlock closed.
  static const IconData lock = IconData(0xE055, fontFamily: fontFamily);

  /// Padlock open.
  static const IconData unlock = IconData(0xE056, fontFamily: fontFamily);

  /// Padlock with a small clock badge (session expired).
  static const IconData lockClock = IconData(0xE057, fontFamily: fontFamily);

  /// Shield with check.
  static const IconData shield = IconData(0xE058, fontFamily: fontFamily);

  /// Gear, 6 rounded teeth.
  static const IconData settings = IconData(0xE059, fontFamily: fontFamily);

  /// Door + arrow leaving toward the end side.
  static const IconData logout = IconData(
    0xE05A,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Speech bubble with "A" + Arabic-ish stroke? no letters: globe with meridians.
  static const IconData language = IconData(0xE05B, fontFamily: fontFamily);

  /// Wifi arcs with a slash.
  static const IconData offline = IconData(0xE05C, fontFamily: fontFamily);

  /// Wifi arcs.
  static const IconData wifi = IconData(0xE05D, fontFamily: fontFamily);

  /// Microphone.
  static const IconData mic = IconData(0xE05E, fontFamily: fontFamily);

  /// Rounded square.
  static const IconData stop = IconData(0xE05F, fontFamily: fontFamily);

  /// Rounded square in a circle.
  static const IconData stopCircle = IconData(0xE060, fontFamily: fontFamily);

  /// 5 vertical bars of varied height.
  static const IconData waveform = IconData(0xE061, fontFamily: fontFamily);

  /// Camera body + lens.
  static const IconData camera = IconData(0xE062, fontFamily: fontFamily);

  /// Thumb up outline.
  static const IconData thumbUp = IconData(0xE063, fontFamily: fontFamily);

  /// Solid thumb up.
  static const IconData thumbUpFill = IconData(0xE064, fontFamily: fontFamily);

  /// Thumb down outline.
  static const IconData thumbDown = IconData(0xE065, fontFamily: fontFamily);

  /// Solid thumb down.
  static const IconData thumbDownFill = IconData(
    0xE066,
    fontFamily: fontFamily,
  );

  /// Finger pointer tapping, 2 ripple arcs.
  static const IconData tap = IconData(0xE067, fontFamily: fontFamily);

  /// Waving hand.
  static const IconData wave = IconData(0xE068, fontFamily: fontFamily);

  /// Phone with side vibration lines.
  static const IconData vibration = IconData(0xE069, fontFamily: fontFamily);

  /// Light bulb.
  static const IconData lightbulb = IconData(0xE06A, fontFamily: fontFamily);

  /// Sun disc + 8 rays.
  static const IconData sun = IconData(0xE06B, fontFamily: fontFamily);

  /// Half sun on a horizon line + 3 rays.
  static const IconData sunrise = IconData(0xE06C, fontFamily: fontFamily);

  /// Crescent moon + small star.
  static const IconData moon = IconData(0xE06D, fontFamily: fontFamily);

  /// Flag on a pole.
  static const IconData flag = IconData(0xE06E, fontFamily: fontFamily);

  /// < / > brackets.
  static const IconData code = IconData(0xE06F, fontFamily: fontFamily);

  /// Leaf with a vein.
  static const IconData leaf = IconData(0xE070, fontFamily: fontFamily);

  /// Egg + small cut line.
  static const IconData egg = IconData(0xE071, fontFamily: fontFamily);

  /// Cup with steam.
  static const IconData coffee = IconData(0xE072, fontFamily: fontFamily);

  /// Fork + knife.
  static const IconData cutlery = IconData(0xE073, fontFamily: fontFamily);

  /// Cooking pot with lid.
  static const IconData recipe = IconData(0xE074, fontFamily: fontFamily);

  /// Cake with a candle.
  static const IconData cake = IconData(0xE075, fontFamily: fontFamily);

  /// Party popper.
  static const IconData party = IconData(0xE076, fontFamily: fontFamily);

  /// Spray bottle.
  static const IconData cleaning = IconData(0xE077, fontFamily: fontFamily);

  /// The assistant: mascot gumdrop with a sparkle.
  static const IconData assistant = IconData(0xE078, fontFamily: fontFamily);

  /// Choose options: three jar sizes.
  static const IconData options = IconData(0xE079, fontFamily: fontFamily);

  /// All categories: four tiles.
  static const IconData categoryAll = IconData(0xE07A, fontFamily: fontFamily);

  /// Crosshair: ring + centre dot + 4 short ticks.
  static const IconData myLocation = IconData(0xE07C, fontFamily: fontFamily);

  /// Office block: tall rounded building, four window dots, arched door.
  static const IconData office = IconData(0xE0AD, fontFamily: fontFamily);

  /// Banknote: rounded note with a coin circle in the middle.
  static const IconData cash = IconData(0xE0AE, fontFamily: fontFamily);

  /// Medal: round disc with a star, ribbon on top.
  static const IconData medal = IconData(0xE0AF, fontFamily: fontFamily);

  /// Arrow down into an open tray (save a file to the device).
  static const IconData download = IconData(0xE0D5, fontFamily: fontFamily);

  /// Arrow up out of an open box (the system share sheet).
  static const IconData share = IconData(0xE0D6, fontFamily: fontFamily);

  /// Printer: paper in at the top, a sheet out at the bottom.
  static const IconData printer = IconData(0xE0D7, fontFamily: fontFamily);

  /// Apartment block: a tall tower beside a lower block, window dots in a column in each.
  static const IconData apartment = IconData(0xE0D8, fontFamily: fontFamily);

  /// Location arrow: an arrowhead pointing up and to the right with a notched tail (find me).
  static const IconData navigation = IconData(0xE0DA, fontFamily: fontFamily);

  // Two-tone accent layers (src/<name>.accent.svg): drawn under the line glyph in a soft tone.

  /// Two-tone layer under [home].
  static const IconData homeAccent = IconData(0xE07D, fontFamily: fontFamily);

  /// Two-tone layer under [bag].
  static const IconData bagAccent = IconData(0xE07E, fontFamily: fontFamily);

  /// Two-tone layer under [cart].
  static const IconData cartAccent = IconData(0xE07F, fontFamily: fontFamily);

  /// Two-tone layer under [basket].
  static const IconData basketAccent = IconData(0xE080, fontFamily: fontFamily);

  /// Two-tone layer under [store].
  static const IconData storeAccent = IconData(0xE081, fontFamily: fontFamily);

  /// Two-tone layer under [orders].
  static const IconData ordersAccent = IconData(0xE082, fontFamily: fontFamily);

  /// Two-tone layer under [receipt].
  static const IconData receiptAccent = IconData(
    0xE083,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [delivery].
  static const IconData deliveryAccent = IconData(
    0xE084,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [pin].
  static const IconData pinAccent = IconData(0xE085, fontFamily: fontFamily);

  /// Two-tone layer under [clock].
  static const IconData clockAccent = IconData(0xE086, fontFamily: fontFamily);

  /// Two-tone layer under [calendar].
  static const IconData calendarAccent = IconData(
    0xE087,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [star].
  static const IconData starAccent = IconData(0xE088, fontFamily: fontFamily);

  /// Two-tone layer under [points].
  static const IconData pointsAccent = IconData(0xE089, fontFamily: fontFamily);

  /// Two-tone layer under [heart].
  static const IconData heartAccent = IconData(0xE08A, fontFamily: fontFamily);

  /// Two-tone layer under [gift].
  static const IconData giftAccent = IconData(0xE08B, fontFamily: fontFamily);

  /// Two-tone layer under [tag].
  static const IconData tagAccent = IconData(0xE08C, fontFamily: fontFamily);

  /// Two-tone layer under [voucher].
  static const IconData voucherAccent = IconData(
    0xE08D,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [discount].
  static const IconData discountAccent = IconData(
    0xE08E,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [wallet].
  static const IconData walletAccent = IconData(0xE08F, fontFamily: fontFamily);

  /// Two-tone layer under [savings].
  static const IconData savingsAccent = IconData(
    0xE090,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [crown].
  static const IconData crownAccent = IconData(0xE091, fontFamily: fontFamily);

  /// Two-tone layer under [bolt].
  static const IconData boltAccent = IconData(0xE092, fontFamily: fontFamily);

  /// Two-tone layer under [flame].
  static const IconData flameAccent = IconData(0xE093, fontFamily: fontFamily);

  /// Two-tone layer under [sparkle].
  static const IconData sparkleAccent = IconData(
    0xE094,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [rocket].
  static const IconData rocketAccent = IconData(0xE095, fontFamily: fontFamily);

  /// Two-tone layer under [person].
  static const IconData personAccent = IconData(0xE096, fontFamily: fontFamily);

  /// Two-tone layer under [people].
  static const IconData peopleAccent = IconData(0xE097, fontFamily: fontFamily);

  /// Two-tone layer under [support].
  static const IconData supportAccent = IconData(
    0xE098,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [chat].
  static const IconData chatAccent = IconData(0xE099, fontFamily: fontFamily);

  /// Two-tone layer under [mail].
  static const IconData mailAccent = IconData(0xE09A, fontFamily: fontFamily);

  /// Two-tone layer under [bell].
  static const IconData bellAccent = IconData(0xE09B, fontFamily: fontFamily);

  /// Two-tone layer under [megaphone].
  static const IconData megaphoneAccent = IconData(
    0xE09C,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [inbox].
  static const IconData inboxAccent = IconData(0xE09D, fontFamily: fontFamily);

  /// Two-tone layer under [document].
  static const IconData documentAccent = IconData(
    0xE09E,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [lock].
  static const IconData lockAccent = IconData(0xE09F, fontFamily: fontFamily);

  /// Two-tone layer under [shield].
  static const IconData shieldAccent = IconData(0xE0A0, fontFamily: fontFamily);

  /// Two-tone layer under [settings].
  static const IconData settingsAccent = IconData(
    0xE0A1,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [camera].
  static const IconData cameraAccent = IconData(0xE0A2, fontFamily: fontFamily);

  /// Two-tone layer under [lightbulb].
  static const IconData lightbulbAccent = IconData(
    0xE0A3,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [sun].
  static const IconData sunAccent = IconData(0xE0A4, fontFamily: fontFamily);

  /// Two-tone layer under [moon].
  static const IconData moonAccent = IconData(0xE0A5, fontFamily: fontFamily);

  /// Two-tone layer under [leaf].
  static const IconData leafAccent = IconData(0xE0A6, fontFamily: fontFamily);

  /// Two-tone layer under [egg].
  static const IconData eggAccent = IconData(0xE0A7, fontFamily: fontFamily);

  /// Two-tone layer under [coffee].
  static const IconData coffeeAccent = IconData(0xE0A8, fontFamily: fontFamily);

  /// Two-tone layer under [recipe].
  static const IconData recipeAccent = IconData(0xE0A9, fontFamily: fontFamily);

  /// Two-tone layer under [cake].
  static const IconData cakeAccent = IconData(0xE0AA, fontFamily: fontFamily);

  /// Two-tone layer under [party].
  static const IconData partyAccent = IconData(0xE0AB, fontFamily: fontFamily);

  /// Two-tone layer under [cleaning].
  static const IconData cleaningAccent = IconData(
    0xE0AC,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [cash].
  static const IconData cashAccent = IconData(0xE0B0, fontFamily: fontFamily);

  /// Two-tone layer under [medal].
  static const IconData medalAccent = IconData(0xE0B1, fontFamily: fontFamily);

  /// Two-tone layer under [closeCircle].
  static const IconData closeCircleAccent = IconData(
    0xE0B2,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [minusCircle].
  static const IconData minusCircleAccent = IconData(
    0xE0B3,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [checkCircle].
  static const IconData checkCircleAccent = IconData(
    0xE0B4,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [info].
  static const IconData infoAccent = IconData(0xE0B5, fontFamily: fontFamily);

  /// Two-tone layer under [warning].
  static const IconData warningAccent = IconData(
    0xE0B6,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [help].
  static const IconData helpAccent = IconData(
    0xE0B7,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// Two-tone layer under [search].
  static const IconData searchAccent = IconData(0xE0B8, fontFamily: fontFamily);

  /// Two-tone layer under [history].
  static const IconData historyAccent = IconData(
    0xE0B9,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [copy].
  static const IconData copyAccent = IconData(0xE0BA, fontFamily: fontFamily);

  /// Two-tone layer under [edit].
  static const IconData editAccent = IconData(0xE0BB, fontFamily: fontFamily);

  /// Two-tone layer under [trash].
  static const IconData trashAccent = IconData(0xE0BC, fontFamily: fontFamily);

  /// Two-tone layer under [ordersDone].
  static const IconData ordersDoneAccent = IconData(
    0xE0BD,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [hourglass].
  static const IconData hourglassAccent = IconData(
    0xE0BE,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [calendarCheck].
  static const IconData calendarCheckAccent = IconData(
    0xE0BF,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [category].
  static const IconData categoryAccent = IconData(
    0xE0C0,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [phone].
  static const IconData phoneAccent = IconData(0xE0C1, fontFamily: fontFamily);

  /// Two-tone layer under [chatAdd].
  static const IconData chatAddAccent = IconData(
    0xE0C2,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [unlock].
  static const IconData unlockAccent = IconData(0xE0C3, fontFamily: fontFamily);

  /// Two-tone layer under [lockClock].
  static const IconData lockClockAccent = IconData(
    0xE0C4,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [language].
  static const IconData languageAccent = IconData(
    0xE0C5,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [mic].
  static const IconData micAccent = IconData(0xE0C6, fontFamily: fontFamily);

  /// Two-tone layer under [stop].
  static const IconData stopAccent = IconData(0xE0C7, fontFamily: fontFamily);

  /// Two-tone layer under [stopCircle].
  static const IconData stopCircleAccent = IconData(
    0xE0C8,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [thumbUp].
  static const IconData thumbUpAccent = IconData(
    0xE0C9,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [thumbDown].
  static const IconData thumbDownAccent = IconData(
    0xE0CA,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [tap].
  static const IconData tapAccent = IconData(0xE0CB, fontFamily: fontFamily);

  /// Two-tone layer under [wave].
  static const IconData waveAccent = IconData(0xE0CC, fontFamily: fontFamily);

  /// Two-tone layer under [vibration].
  static const IconData vibrationAccent = IconData(
    0xE0CD,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [sunrise].
  static const IconData sunriseAccent = IconData(
    0xE0CE,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [flag].
  static const IconData flagAccent = IconData(0xE0CF, fontFamily: fontFamily);

  /// Two-tone layer under [assistant].
  static const IconData assistantAccent = IconData(
    0xE0D0,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [options].
  static const IconData optionsAccent = IconData(
    0xE0D1,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [categoryAll].
  static const IconData categoryAllAccent = IconData(
    0xE0D2,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [myLocation].
  static const IconData myLocationAccent = IconData(
    0xE0D3,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [office].
  static const IconData officeAccent = IconData(0xE0D4, fontFamily: fontFamily);

  /// Two-tone layer under [apartment].
  static const IconData apartmentAccent = IconData(
    0xE0D9,
    fontFamily: fontFamily,
  );

  /// Two-tone layer under [navigation].
  static const IconData navigationAccent = IconData(
    0xE0DB,
    fontFamily: fontFamily,
  );

  // Aliases (tool/icons/aliases.json): another name for a drawn glyph.

  /// The [delivery] glyph, flipped in RTL.
  static const IconData deliveryDirectional = IconData(
    0xE02C,
    fontFamily: fontFamily,
    matchTextDirection: true,
  );

  /// The [person] glyph.
  static const IconData account = IconData(0xE049, fontFamily: fontFamily);

  /// The two-tone accent layer drawn under [icon], or `null` when [icon] has none or is not
  /// a Hero glyph. Aliases resolve through their codepoint (`account` → `personAccent`).
  static IconData? accentOf(IconData icon) => _accentOf(icon);

  /// The natural colour of [icon]'s accent layer (concepts.tsv `fill`); `null` exactly when
  /// [accentOf] is `null`.
  static HeroIconFill? fillOf(IconData icon) => _fillOf(icon);

  /// Every constant above by its source name (glyphs, accent layers, aliases), for tests and
  /// tooling that walk the whole font.
  static const Map<String, IconData> byName = <String, IconData>{
    'back': back,
    'arrowForward': arrowForward,
    'arrowUp': arrowUp,
    'arrowDown': arrowDown,
    'arrowUpStart': arrowUpStart,
    'arrowUpEnd': arrowUpEnd,
    'chevronEnd': chevronEnd,
    'chevronStart': chevronStart,
    'chevronDown': chevronDown,
    'chevronUp': chevronUp,
    'close': close,
    'closeCircle': closeCircle,
    'closeCircleFill': closeCircleFill,
    'plus': plus,
    'minus': minus,
    'minusCircle': minusCircle,
    'check': check,
    'checkDouble': checkDouble,
    'checkCircle': checkCircle,
    'checkCircleFill': checkCircleFill,
    'info': info,
    'warning': warning,
    'exclamation': exclamation,
    'help': help,
    'search': search,
    'filter': filter,
    'sort': sort,
    'swapHorizontal': swapHorizontal,
    'moreVertical': moreVertical,
    'refresh': refresh,
    'history': history,
    'copy': copy,
    'edit': edit,
    'trash': trash,
    'home': home,
    'homeFill': homeFill,
    'bag': bag,
    'cart': cart,
    'cartAdd': cartAdd,
    'basket': basket,
    'store': store,
    'orders': orders,
    'ordersDone': ordersDone,
    'receipt': receipt,
    'delivery': delivery,
    'pin': pin,
    'pinFill': pinFill,
    'clock': clock,
    'hourglass': hourglass,
    'calendar': calendar,
    'calendarCheck': calendarCheck,
    'star': star,
    'starFill': starFill,
    'points': points,
    'pointsFill': pointsFill,
    'heart': heart,
    'heartFill': heartFill,
    'gift': gift,
    'tag': tag,
    'voucher': voucher,
    'percent': percent,
    'discount': discount,
    'wallet': wallet,
    'savings': savings,
    'crown': crown,
    'bolt': bolt,
    'flame': flame,
    'flameFill': flameFill,
    'sparkle': sparkle,
    'rocket': rocket,
    'trendingUp': trendingUp,
    'category': category,
    'person': person,
    'people': people,
    'support': support,
    'phone': phone,
    'chat': chat,
    'chatFill': chatFill,
    'chatAdd': chatAdd,
    'mail': mail,
    'bell': bell,
    'megaphone': megaphone,
    'inbox': inbox,
    'document': document,
    'lock': lock,
    'unlock': unlock,
    'lockClock': lockClock,
    'shield': shield,
    'settings': settings,
    'logout': logout,
    'language': language,
    'offline': offline,
    'wifi': wifi,
    'mic': mic,
    'stop': stop,
    'stopCircle': stopCircle,
    'waveform': waveform,
    'camera': camera,
    'thumbUp': thumbUp,
    'thumbUpFill': thumbUpFill,
    'thumbDown': thumbDown,
    'thumbDownFill': thumbDownFill,
    'tap': tap,
    'wave': wave,
    'vibration': vibration,
    'lightbulb': lightbulb,
    'sun': sun,
    'sunrise': sunrise,
    'moon': moon,
    'flag': flag,
    'code': code,
    'leaf': leaf,
    'egg': egg,
    'coffee': coffee,
    'cutlery': cutlery,
    'recipe': recipe,
    'cake': cake,
    'party': party,
    'cleaning': cleaning,
    'assistant': assistant,
    'options': options,
    'categoryAll': categoryAll,
    'myLocation': myLocation,
    'homeAccent': homeAccent,
    'bagAccent': bagAccent,
    'cartAccent': cartAccent,
    'basketAccent': basketAccent,
    'storeAccent': storeAccent,
    'ordersAccent': ordersAccent,
    'receiptAccent': receiptAccent,
    'deliveryAccent': deliveryAccent,
    'pinAccent': pinAccent,
    'clockAccent': clockAccent,
    'calendarAccent': calendarAccent,
    'starAccent': starAccent,
    'pointsAccent': pointsAccent,
    'heartAccent': heartAccent,
    'giftAccent': giftAccent,
    'tagAccent': tagAccent,
    'voucherAccent': voucherAccent,
    'discountAccent': discountAccent,
    'walletAccent': walletAccent,
    'savingsAccent': savingsAccent,
    'crownAccent': crownAccent,
    'boltAccent': boltAccent,
    'flameAccent': flameAccent,
    'sparkleAccent': sparkleAccent,
    'rocketAccent': rocketAccent,
    'personAccent': personAccent,
    'peopleAccent': peopleAccent,
    'supportAccent': supportAccent,
    'chatAccent': chatAccent,
    'mailAccent': mailAccent,
    'bellAccent': bellAccent,
    'megaphoneAccent': megaphoneAccent,
    'inboxAccent': inboxAccent,
    'documentAccent': documentAccent,
    'lockAccent': lockAccent,
    'shieldAccent': shieldAccent,
    'settingsAccent': settingsAccent,
    'cameraAccent': cameraAccent,
    'lightbulbAccent': lightbulbAccent,
    'sunAccent': sunAccent,
    'moonAccent': moonAccent,
    'leafAccent': leafAccent,
    'eggAccent': eggAccent,
    'coffeeAccent': coffeeAccent,
    'recipeAccent': recipeAccent,
    'cakeAccent': cakeAccent,
    'partyAccent': partyAccent,
    'cleaningAccent': cleaningAccent,
    'office': office,
    'cash': cash,
    'medal': medal,
    'cashAccent': cashAccent,
    'medalAccent': medalAccent,
    'closeCircleAccent': closeCircleAccent,
    'minusCircleAccent': minusCircleAccent,
    'checkCircleAccent': checkCircleAccent,
    'infoAccent': infoAccent,
    'warningAccent': warningAccent,
    'helpAccent': helpAccent,
    'searchAccent': searchAccent,
    'historyAccent': historyAccent,
    'copyAccent': copyAccent,
    'editAccent': editAccent,
    'trashAccent': trashAccent,
    'ordersDoneAccent': ordersDoneAccent,
    'hourglassAccent': hourglassAccent,
    'calendarCheckAccent': calendarCheckAccent,
    'categoryAccent': categoryAccent,
    'phoneAccent': phoneAccent,
    'chatAddAccent': chatAddAccent,
    'unlockAccent': unlockAccent,
    'lockClockAccent': lockClockAccent,
    'languageAccent': languageAccent,
    'micAccent': micAccent,
    'stopAccent': stopAccent,
    'stopCircleAccent': stopCircleAccent,
    'thumbUpAccent': thumbUpAccent,
    'thumbDownAccent': thumbDownAccent,
    'tapAccent': tapAccent,
    'waveAccent': waveAccent,
    'vibrationAccent': vibrationAccent,
    'sunriseAccent': sunriseAccent,
    'flagAccent': flagAccent,
    'assistantAccent': assistantAccent,
    'optionsAccent': optionsAccent,
    'categoryAllAccent': categoryAllAccent,
    'myLocationAccent': myLocationAccent,
    'officeAccent': officeAccent,
    'download': download,
    'share': share,
    'printer': printer,
    'apartment': apartment,
    'apartmentAccent': apartmentAccent,
    'navigation': navigation,
    'navigationAccent': navigationAccent,
    'deliveryDirectional': deliveryDirectional,
    'account': account,
  };
}

// Outside [HeroIcons] on purpose: the icon tree shaker skips the body of a @staticIconProvider
// class, so the accent constants must be referenced from here to stay in the release font.
IconData? _accentOf(IconData icon) {
  if (icon.fontFamily != HeroIcons.fontFamily) return null;
  final IconData? accent = switch (icon.codePoint) {
    0xE022 => HeroIcons.homeAccent,
    0xE024 => HeroIcons.bagAccent,
    0xE025 => HeroIcons.cartAccent,
    0xE027 => HeroIcons.basketAccent,
    0xE028 => HeroIcons.storeAccent,
    0xE029 => HeroIcons.ordersAccent,
    0xE02B => HeroIcons.receiptAccent,
    0xE02C => HeroIcons.deliveryAccent,
    0xE02E => HeroIcons.pinAccent,
    0xE030 => HeroIcons.clockAccent,
    0xE032 => HeroIcons.calendarAccent,
    0xE034 => HeroIcons.starAccent,
    0xE036 => HeroIcons.pointsAccent,
    0xE038 => HeroIcons.heartAccent,
    0xE03A => HeroIcons.giftAccent,
    0xE03B => HeroIcons.tagAccent,
    0xE03C => HeroIcons.voucherAccent,
    0xE03E => HeroIcons.discountAccent,
    0xE03F => HeroIcons.walletAccent,
    0xE040 => HeroIcons.savingsAccent,
    0xE041 => HeroIcons.crownAccent,
    0xE042 => HeroIcons.boltAccent,
    0xE043 => HeroIcons.flameAccent,
    0xE045 => HeroIcons.sparkleAccent,
    0xE046 => HeroIcons.rocketAccent,
    0xE049 => HeroIcons.personAccent,
    0xE04A => HeroIcons.peopleAccent,
    0xE04B => HeroIcons.supportAccent,
    0xE04D => HeroIcons.chatAccent,
    0xE050 => HeroIcons.mailAccent,
    0xE051 => HeroIcons.bellAccent,
    0xE052 => HeroIcons.megaphoneAccent,
    0xE053 => HeroIcons.inboxAccent,
    0xE054 => HeroIcons.documentAccent,
    0xE055 => HeroIcons.lockAccent,
    0xE058 => HeroIcons.shieldAccent,
    0xE059 => HeroIcons.settingsAccent,
    0xE062 => HeroIcons.cameraAccent,
    0xE06A => HeroIcons.lightbulbAccent,
    0xE06B => HeroIcons.sunAccent,
    0xE06D => HeroIcons.moonAccent,
    0xE070 => HeroIcons.leafAccent,
    0xE071 => HeroIcons.eggAccent,
    0xE072 => HeroIcons.coffeeAccent,
    0xE074 => HeroIcons.recipeAccent,
    0xE075 => HeroIcons.cakeAccent,
    0xE076 => HeroIcons.partyAccent,
    0xE077 => HeroIcons.cleaningAccent,
    0xE0AE => HeroIcons.cashAccent,
    0xE0AF => HeroIcons.medalAccent,
    0xE00B => HeroIcons.closeCircleAccent,
    0xE00F => HeroIcons.minusCircleAccent,
    0xE012 => HeroIcons.checkCircleAccent,
    0xE014 => HeroIcons.infoAccent,
    0xE015 => HeroIcons.warningAccent,
    0xE017 => HeroIcons.helpAccent,
    0xE018 => HeroIcons.searchAccent,
    0xE01E => HeroIcons.historyAccent,
    0xE01F => HeroIcons.copyAccent,
    0xE020 => HeroIcons.editAccent,
    0xE021 => HeroIcons.trashAccent,
    0xE02A => HeroIcons.ordersDoneAccent,
    0xE031 => HeroIcons.hourglassAccent,
    0xE033 => HeroIcons.calendarCheckAccent,
    0xE048 => HeroIcons.categoryAccent,
    0xE04C => HeroIcons.phoneAccent,
    0xE04F => HeroIcons.chatAddAccent,
    0xE056 => HeroIcons.unlockAccent,
    0xE057 => HeroIcons.lockClockAccent,
    0xE05B => HeroIcons.languageAccent,
    0xE05E => HeroIcons.micAccent,
    0xE05F => HeroIcons.stopAccent,
    0xE060 => HeroIcons.stopCircleAccent,
    0xE063 => HeroIcons.thumbUpAccent,
    0xE065 => HeroIcons.thumbDownAccent,
    0xE067 => HeroIcons.tapAccent,
    0xE068 => HeroIcons.waveAccent,
    0xE069 => HeroIcons.vibrationAccent,
    0xE06C => HeroIcons.sunriseAccent,
    0xE06E => HeroIcons.flagAccent,
    0xE078 => HeroIcons.assistantAccent,
    0xE079 => HeroIcons.optionsAccent,
    0xE07A => HeroIcons.categoryAllAccent,
    0xE07C => HeroIcons.myLocationAccent,
    0xE0AD => HeroIcons.officeAccent,
    0xE0D8 => HeroIcons.apartmentAccent,
    0xE0DA => HeroIcons.navigationAccent,
    _ => null,
  };
  // An alias with its own direction (deliveryDirectional) would leave its layer unflipped in RTL.
  return accent?.matchTextDirection == icon.matchTextDirection ? accent : null;
}

// Guarded by [_accentOf], so a fill exists exactly where an accent layer is drawn.
HeroIconFill? _fillOf(IconData icon) {
  if (_accentOf(icon) == null) return null;
  return switch (icon.codePoint) {
    0xE022 => HeroIconFill.green,
    0xE024 => HeroIconFill.green,
    0xE025 => HeroIconFill.green,
    0xE027 => HeroIconFill.green,
    0xE028 => HeroIconFill.green,
    0xE029 => HeroIconFill.mint,
    0xE02B => HeroIconFill.mint,
    0xE02C => HeroIconFill.green,
    0xE02E => HeroIconFill.green,
    0xE030 => HeroIconFill.mint,
    0xE032 => HeroIconFill.mint,
    0xE034 => HeroIconFill.amber,
    0xE036 => HeroIconFill.amber,
    0xE038 => HeroIconFill.red,
    0xE03A => HeroIconFill.orange,
    0xE03B => HeroIconFill.orange,
    0xE03C => HeroIconFill.amber,
    0xE03E => HeroIconFill.red,
    0xE03F => HeroIconFill.amber,
    0xE040 => HeroIconFill.amber,
    0xE041 => HeroIconFill.amber,
    0xE042 => HeroIconFill.yellow,
    0xE043 => HeroIconFill.orange,
    0xE045 => HeroIconFill.violet,
    0xE046 => HeroIconFill.orange,
    0xE049 => HeroIconFill.mint,
    0xE04A => HeroIconFill.mint,
    0xE04B => HeroIconFill.mint,
    0xE04D => HeroIconFill.mint,
    0xE050 => HeroIconFill.sky,
    0xE051 => HeroIconFill.yellow,
    0xE052 => HeroIconFill.orange,
    0xE053 => HeroIconFill.sky,
    0xE054 => HeroIconFill.sky,
    0xE055 => HeroIconFill.sky,
    0xE058 => HeroIconFill.mint,
    0xE059 => HeroIconFill.sky,
    0xE062 => HeroIconFill.sky,
    0xE06A => HeroIconFill.yellow,
    0xE06B => HeroIconFill.yellow,
    0xE06D => HeroIconFill.yellow,
    0xE070 => HeroIconFill.green,
    0xE071 => HeroIconFill.cream,
    0xE072 => HeroIconFill.cream,
    0xE074 => HeroIconFill.green,
    0xE075 => HeroIconFill.cream,
    0xE076 => HeroIconFill.yellow,
    0xE077 => HeroIconFill.sky,
    0xE0AE => HeroIconFill.green,
    0xE0AF => HeroIconFill.amber,
    0xE00B => HeroIconFill.red,
    0xE00F => HeroIconFill.mint,
    0xE012 => HeroIconFill.green,
    0xE014 => HeroIconFill.sky,
    0xE015 => HeroIconFill.yellow,
    0xE017 => HeroIconFill.sky,
    0xE018 => HeroIconFill.sky,
    0xE01E => HeroIconFill.mint,
    0xE01F => HeroIconFill.cream,
    0xE020 => HeroIconFill.cream,
    0xE021 => HeroIconFill.cream,
    0xE02A => HeroIconFill.mint,
    0xE031 => HeroIconFill.amber,
    0xE033 => HeroIconFill.mint,
    0xE048 => HeroIconFill.mint,
    0xE04C => HeroIconFill.green,
    0xE04F => HeroIconFill.mint,
    0xE056 => HeroIconFill.sky,
    0xE057 => HeroIconFill.sky,
    0xE05B => HeroIconFill.sky,
    0xE05E => HeroIconFill.mint,
    0xE05F => HeroIconFill.red,
    0xE060 => HeroIconFill.red,
    0xE063 => HeroIconFill.yellow,
    0xE065 => HeroIconFill.yellow,
    0xE067 => HeroIconFill.sky,
    0xE068 => HeroIconFill.yellow,
    0xE069 => HeroIconFill.sky,
    0xE06C => HeroIconFill.orange,
    0xE06E => HeroIconFill.red,
    0xE078 => HeroIconFill.green,
    0xE079 => HeroIconFill.cream,
    0xE07A => HeroIconFill.mint,
    0xE07C => HeroIconFill.sky,
    0xE0AD => HeroIconFill.sky,
    0xE0D8 => HeroIconFill.cream,
    0xE0DA => HeroIconFill.sky,
    _ => null,
  };
}

/// The natural colour of a two-tone icon's accent layer ([HeroIcons.fillOf]), after the sticker
/// art in `assets/svg`. The app maps each value to an `AppColors` token.
enum HeroIconFill {
  /// Brand green, saturated: the brand's own objects (bag, cart, store, delivery, pin, leaf).
  green,

  /// Pale brand mint: soft containers (chat, orders, clock face, person).
  mint,

  /// Gold: value and rewards (star, points, wallet, crown, voucher).
  amber,

  /// Sunny yellow: light and attention (bell, lightbulb, sun, bolt).
  yellow,

  /// Warm orange: treats and heat (gift, tag, flame).
  orange,

  /// Offer red: love and deals (heart, discount), stop and cancel.
  red,

  /// Pale sky blue: information, tools and glass (search lens, mail, info, lock).
  sky,

  /// Pale violet: Pro and magic (sparkle).
  violet,

  /// Warm cream: paper, pantry and utensils (egg, coffee, edit, copy).
  cream,
}
