#!/usr/bin/env node
// =============================================================================
// build_wordmark_glyphs.js — turns the letters of the JameiaMart wordmark into
// Dart `Path` data, so the splash draws the logo as vectors (no font shipped,
// every letter animates on its own).
//
//   cd tool/splash
//   npm i --no-save opentype.js@1.3.4
//   curl -L -o nunito-800.ttf \
//     https://cdn.jsdelivr.net/fontsource/fonts/nunito@latest/latin-800-normal.ttf
//   node build_wordmark_glyphs.js nunito-800.ttf
//
// Writes lib/src/features/splash/presentation/widgets/splash_wordmark_glyphs.dart.
// Letters: "ameıaMart" (the "J" is the cart mark, the "i" is dotless because a
// leaf replaces its dot). Nunito is SIL Open Font License 1.1.
// =============================================================================
'use strict';

const fs = require('fs');
const path = require('path');
const opentype = require('opentype.js');

const fontPath = process.argv[2];
if (!fontPath) {
  console.error('usage: node build_wordmark_glyphs.js <nunito-800.ttf>');
  process.exit(1);
}

const LETTERS = 'ameıaMart';
/** Tighter than the font's own spacing, like the logo (font units). */
const TRACKING = -12;
const OUT = path.join(
  __dirname,
  '..',
  '..',
  'lib/src/features/splash/presentation/widgets/splash_wordmark_glyphs.dart',
);

const font = opentype.loadSync(fontPath);
const r = (v) => {
  const n = Math.round(v * 10) / 10;
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
};

/** Dart cascade for one glyph at pen x = 0, y flipped (y-down, baseline 0). */
function glyphBody(glyph) {
  const lines = [];
  for (const c of glyph.path.commands) {
    switch (c.type) {
      case 'M':
        lines.push(`..moveTo(${r(c.x)}, ${r(-c.y)})`);
        break;
      case 'L':
        lines.push(`..lineTo(${r(c.x)}, ${r(-c.y)})`);
        break;
      case 'Q':
        lines.push(
          `..quadraticBezierTo(${r(c.x1)}, ${r(-c.y1)}, ${r(c.x)}, ${r(-c.y)})`,
        );
        break;
      case 'C':
        lines.push(
          `..cubicTo(${r(c.x1)}, ${r(-c.y1)}, ${r(c.x2)}, ${r(-c.y2)}, ${r(c.x)}, ${r(-c.y)})`,
        );
        break;
      case 'Z':
        lines.push('..close()');
        break;
      default:
        throw new Error(`unknown path command ${c.type}`);
    }
  }
  return lines;
}

const glyphs = [...LETTERS].map((ch) => font.charToGlyph(ch));
const penX = [];
let x = 0;
glyphs.forEach((g, i) => {
  penX.push(x);
  x += g.advanceWidth + TRACKING;
  if (i + 1 < glyphs.length) x += font.getKerningValue(g, glyphs[i + 1]);
});
const width = x - TRACKING;

const unique = new Map();
for (const g of glyphs) if (!unique.has(g.name)) unique.set(g.name, g);
const fnName = (g) => {
  const id = g.name.replace(/[^A-Za-z0-9]/g, '');
  // lowerCamelCase: an uppercase glyph ("M") becomes `_capM`.
  return /^[A-Z]/.test(id) ? `_cap${id}` : `_${id}`;
};

const dotless = [...LETTERS].indexOf('ı');
const dotlessBox = glyphs[dotless].getBoundingBox();

let out = '';
out += '// GENERATED by tool/splash/build_wordmark_glyphs.js — do not edit by hand.\n';
out += '// Outlines: Nunito ExtraBold (SIL Open Font License 1.1,\n';
out += '// © The Nunito Project Authors). Font units, y down, baseline at 0.\n';
out += "import 'dart:ui';\n\n";
out += '/// The letters after the cart "J" of the JameiaMart wordmark ("ameıaMart"),\n';
out += '/// as vector outlines in font units ([unitsPerEm] per em, y down, baseline\n';
out += '/// at 0). Each path already sits at its pen position along the line.\n';
out += 'abstract final class SplashWordmarkGlyphs {\n';
out += `  static const double unitsPerEm = ${r(font.unitsPerEm)};\n`;
out += `  static const double capHeight = ${r(font.tables.os2.sCapHeight)};\n`;
out += `  static const double xHeight = ${r(font.tables.os2.sxHeight)};\n\n`;
out += '  /// Advance of the whole line, from the first pen position to the end of\n';
out += '  /// the last letter.\n';
out += `  static const double width = ${r(width)};\n\n`;
out += '  /// Index of the dotless "ı" that carries the leaf.\n';
out += `  static const int leafLetter = ${dotless};\n\n`;
out += '  /// Horizontal centre and top of the "ı" stem (font units, y down).\n';
out += `  static const double leafStemX = ${r(penX[dotless] + (dotlessBox.x1 + dotlessBox.x2) / 2)};\n`;
out += `  static const double leafStemTop = ${r(-dotlessBox.y2)};\n\n`;
out += '  /// One path per letter, in reading order.\n';
out += '  static final List<Path> letters = <Path>[\n';
glyphs.forEach((g, i) => {
  out += `    ${fnName(g)}().shift(const Offset(${r(penX[i])}, 0)),\n`;
});
out += '  ];\n';
for (const g of unique.values()) {
  out += `\n  static Path ${fnName(g)}() => Path()\n`;
  const body = glyphBody(g);
  body.forEach((line, i) => {
    out += `    ${line}${i === body.length - 1 ? ';' : ''}\n`;
  });
}
out += '}\n';

fs.writeFileSync(OUT, out);
console.log(`wrote ${path.relative(process.cwd(), OUT)} — width ${r(width)}`);
